nome = input("Digite o nome do funcionario: ")
codigo = int(input("Digite o código do funcionario: "))
idade =  int(input("Digite a idade do funcionario: "))
salario = float(input("Digite o salário do funcionario: "))
sexo =  input("Digite o sexo (F ou M): ")
numerofilhos = int(input("Digite o numero de filhos do funcionario: "))
estadocivil = input("Digite o estado civil do funcionario: ")

print("Nome do funcionario:", nome)
print("Código do funcionario: ", codigo)
print("Idade do funcionario", idade)
print("Salário do funcionario", salario)
print("Sexo do funcionario: ", sexo)
print("Numero de filhos do funcionario: ", numerofilhos)
print("Estado civil do funcionario: ", estadocivil)